#!/usr/bin/env python
import matplotlib.pyplot as plt
import sys

def make_plot(data):
    l = len(data) / 2
    plt.plot([i for i in xrange(l)], data[:l]) # don't need back half of fft
    plt.show()

if __name__ == "__main__":
    data = []
    if len(sys.argv) > 1:
        f = open(sys.argv[1])
        data = [float(line) for line in f]
        f.close()
    else:
        data = [float(line) for line in sys.stdin]
    make_plot(data)
